version: "3.8"

services:
  laser-be:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT:-3000}:3000"
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - MONGODB_URL=${MONGODB_URL:-mongodb://mongodb:27017}
      - MONGODB_DATABASE=${MONGODB_DATABASE:-main-data}
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

volumes:
  mongo_data:

networks:
  app-network:
    driver: bridge
